// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi_4WKgJGlzaG_G5NlBm10qBU3I1-8Idc',
    appId: '1:152050584231:web:0814b49d25fa6ff838a982',
    messagingSenderId: '152050584231',
    projectId: 'moneyque-19585',
    authDomain: 'moneyque-19585.firebaseapp.com',
    storageBucket: 'moneyque-19585.appspot.com',
    measurementId: 'G-LGL4BWQMX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCyNY7uXIhp3VDMCD_oVHY-KuXeId9zs',
    appId: '1:152050584231:android:74cf3682c6e6765438a982',
    messagingSenderId: '152050584231',
    projectId: 'moneyque-19585',
    storageBucket: 'moneyque-19585.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFo58rKQCrT9ANzr3wPCbS7Ig8rj765o',
    appId: '1:152050584231:ios:bb6d95cd474e410a38a982',
    messagingSenderId: '152050584231',
    projectId: 'moneyque-19585',
    storageBucket: 'moneyque-19585.appspot.com',
    androidClientId: '152050584231-j2arftj8ar9mg77u3b9j9eh4260q4d7h.apps.googleusercontent.com',
    iosClientId: '152050584231-sekmq9p60519vcebvvku946tfp67a8kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyque',
  );
}
